// Quick look: new world from a seed, look around, walk, screenshots.
import { chromium } from 'playwright-core';
import { pathToFileURL } from 'node:url';
import { resolve } from 'node:path';
import { mkdirSync } from 'node:fs';
const out = process.argv[2] || 'test-output/pokecraft';
mkdirSync(out, { recursive: true });
const exe = process.env.CHROMIUM || '/opt/pw-browsers/chromium-1194/chrome-linux/chrome';
const browser = await chromium.launch({ executablePath: exe, args: ['--autoplay-policy=no-user-gesture-required', '--use-gl=angle', '--use-angle=swiftshader', '--enable-unsafe-swiftshader'] });
const landscape = process.env.LANDSCAPE === '1';
const ctx = await browser.newContext({ viewport: landscape ? { width: 844, height: 390 } : { width: 390, height: 844 }, deviceScaleFactor: 2, isMobile: true, hasTouch: true });
const page = await ctx.newPage();
const errors = [];
page.on('pageerror', (e) => errors.push(`pageerror: ${e.message}`));
page.on('console', (m) => { if (m.type() === 'error' && !/fonts\.g|ERR_/.test(m.text())) errors.push(m.text()); });
const g = (fn, arg) => page.evaluate(fn, arg);
const t0 = Date.now();
await page.goto(pathToFileURL(resolve('pokecraft/dist/index.html')).href);
await page.waitForSelector('#title .menu:not([hidden])', { timeout: 60000 });
console.log('title after', Date.now() - t0, 'ms');
await page.click('#btn-new');
await page.fill('#seed', process.env.SEED || 'gamemosh');
const t1 = Date.now();
await page.click('#starters button[data-starter="squirtle"]');
await page.waitForFunction(() => window.__pc.mode === 'world', null, { timeout: 180000 });
console.log('world after', Date.now() - t1, 'ms', await g(() => JSON.stringify({ pos: __pc.player.pos.map((v) => +v.toFixed(1)), mode: __pc.world.mode, meshes: __pc.world.stats })));
await page.waitForTimeout(4000);
await g(() => { document.getElementById('toast').hidden = true; });
await page.screenshot({ path: `${out}/s1-spawn.png` });
await g(() => { __pc.player.yaw += Math.PI; __pc.player.pitch = -0.2; });
await page.waitForTimeout(1500);
await page.screenshot({ path: `${out}/s2-turn.png` });
await page.keyboard.down('KeyW'); await page.waitForTimeout(3000); await page.keyboard.up('KeyW');
await page.waitForTimeout(1000);
console.log('after walk', await g(() => JSON.stringify({ pos: __pc.player.pos.map((v) => +v.toFixed(1)), ents: __pc.ents.list.map((e) => e.kind + ':' + (e.species || e.npc)).slice(0, 10), chunks: __pc.world.chunks.size, frames: __pc.frames })));
await page.screenshot({ path: `${out}/s3-walk.png` });
console.log(errors.length ? `ERRORS:\n${errors.join('\n')}` : 'SMOKE OK');
await browser.close();
